# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Robotathon Docs
email: ut.ieee.ras@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://ut.ieee.ras.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs

# favicon_ico: "/_assets/images/favicon.ico"

livereload: true
search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files despite having a preceding underscore in directory name
include:
  - _assets # Example of including _assets directory

# Collections for website data
collections_dir: _sections
collections:
  guide-general:
    permalink: "/:path"
    output: true
    sort: nav_order
  guide-primaries:
    permalink: "/:path"
    output: true
  guide-supplementals:
    permalink: "/:path"
    output: true

# Define which collections are used in just-the-docs
just_the_docs:
  collections:
    guide-general:
      name: Home
      nav_fold: false
    guide-primaries:
      name: Newbie Guide
      nav_fold: false
    guide-supplementals:
      name: Resources
      nav_fold: false

# Define sass
sass:
  load_paths:
    - _sass/
    - node_modules/@catppuccin/palette/scss/

# Define default color scheme
color_scheme: catppuccin_latte
